# Generated by Django 4.1.2 on 2022-12-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='parent_skills',
            field=models.ManyToManyField(blank=True, to='skill_set.skill'),
        ),
    ]
