# Generated by Django 4.1.2 on 2022-12-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_set', '0002_lesson_description_alter_skill_parent_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='parent_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill_set.lesson'),
        ),
    ]
