# Generated by Django 4.1.2 on 2022-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_set', '0005_remove_skill_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skill_set.skill'),
        ),
    ]
