# Generated by Django 4.1.2 on 2023-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_set', '0008_rename_link_lesson_code_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='app_link',
            field=models.URLField(blank=True),
        ),
    ]
