# Generated by Django 4.2.6 on 2023-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_set', '0009_lesson_app_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
