# Generated by Django 4.1.2 on 2022-11-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastOpened', models.DateTimeField(default=django.utils.timezone.now)),
                ('timesOpened', models.IntegerField(default=1)),
                ('collapsed', models.BooleanField(default=True)),
                ('seeingActionables', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parentContainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook_2.container')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionable', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('statement', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parentContainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook_2.container')),
                ('parentItem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook_2.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parentItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook_2.item')),
            ],
        ),
    ]
