# Generated by Django 4.1.2 on 2022-11-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_2', '0003_alter_item_parentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parentItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook_2.item'),
        ),
    ]
