# Generated by Django 4.1.2 on 2022-12-15 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook_2', '0005_alter_itemstatementversion_parentitem_tag_item_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemStatementVersion',
            new_name='StatementVersion',
        ),
    ]
