# Generated by Django 4.1.2 on 2023-01-20 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook_2', '0007_item_statement_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ItemTag',
        ),
    ]
